### ISSUE TITLE
Upgrade to v3.0 won't work

### ISSUE THREAD

**Issue by jpmurray** [bytefury/crater#166] opened 2020-02-14 10:51 UTC
**Describe the bug**
Hitting the check for update button gives me an available one for 3.0.0. Hitting the button to do the update will show crater trying to update itself, but stops. Here is the error logs (without stacktrace) that happens:

```
[2020-02-14 10:43:55] production.ERROR: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'units' already exists (SQL: create table `units` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `company_id` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci') {"userId":1,"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'units' already exists (SQL: create table `units` (`id` int unsigned not null auto_increment primary key, `name` varchar(255) not null, `company_id` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate 'utf8_unicode_ci') at /home/user/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665)

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'units' already exists at /home/user/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:123)

[previous exception] [object] (PDOException(code: 42S01): SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'units' already exists at /home/user/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:121)
```

**Expected behavior**
Crater should be updating. I hope! :)

**Please complete the following information:**
- Crater version: 2.1.0
- PHP version: 7.2.24
- Database type and version: Mysql 5.7.29

**Optional info**
- OS:  Ubuntu 18.4.03

**Comment by mohitpanjwani** [comment] 2020-02-17 18:57
Hey! Update seems to work perfectly for us but we are trying to reproduce the issue.

**Comment by jpmurray** [comment] 2020-02-18 21:03
I installed via Git, if it changes anything.

**Comment by mohitpanjwani** [comment] 2020-04-27 06:41
@jpmurray Did you manage to find a workaround for this? Sorry, I forgot about this issue. 

I think the update failed for you because we forgot to update the version number for an hour and pushed the changes on GitHub by mistake. 

You must have cloned the repository exactly on that hour before we released the fix. So when we released the new update you already had the new units table so when you tried to run the self-update it caused an error as you already made some changes to it. 

We're working on making things more modular and performing some checks before running the update to avoid this kind of issue in future.

Right now we have 2 ways to install crater: 
- via cloning GIT repo
- downloading the zip file version

A lot of manual work is required in order to main both of these versions (especially the zip file version) so I'm looking for ways to improve this workflow.

**Comment by jpmurray** [comment] 2020-04-28 16:25
That might make sense. I did not do anything else, decided that status quo was better for now.

I'll probably reinstall entierly sooner or later. Do you think exporting database and reimporting over a new install would work?

**Comment by mohitpanjwani** [comment] 2020-05-11 07:22
That should work but I suppose you must have already got the latest changes from 3.0.0. 

So I think you can just try to update the database manually by changing the app `version` column on settings table to `3.0.0`

**Comment by mohitpanjwani** [comment] 2020-05-12 08:06
I'll close this issue but if there's any other problem.. Please feel free to comment or send me a message on discord. 

Thanks

**Closed by mohitpanjwani** 2020-05-12 08:06 UTC

**Comment by jpmurray** [comment] 2020-05-12 11:38
Perfect ! I should be testing this in before the weekend if I'm lucky. I'll pop on Discord if anything goes awry.
