### ISSUE TITLE
Blank PDFs

### ISSUE THREAD

**Issue by stanier** [bytefury/crater#95] opened 2019-12-23 06:55 UTC
**Describe the bug**
When viewing an invoice, or if a customer receives an invoice, the PDF of it is blank

**Expected behavior**
It is expected to show the invoice as compiled per the template

**Screenshots**
![image](https://user-images.githubusercontent.com/8770519/71341159-0ec58780-2527-11ea-86ce-c6aaa64a99df.png)

**Please complete the following information:**
- Crater version: 2.1.0
- PHP version: latest in docker
- Database type and version: MySQL, latest in docker

**Optional info**
- OS:  Docker on Ubuntu 18.04
- Browser: Firefox, Vivaldi

**Comment by halloalexkern** [comment] 2019-12-23 20:36
Same here. Similar setup.
No errors in Browser Console or Docker logs.

**Comment by BirkhoffLee** [comment] 2019-12-24 10:06
Duplicate to #69

**Comment by ndmacioce** [comment] 2019-12-30 17:22
Experiencing same.

**Comment by proea** [comment] 2020-02-02 20:37
This issues it duplicate of #69 and should be closed.

#69 was fixed.

**Closed** 2020-05-12 08:14 UTC
