### ISSUE TITLE
Editing expenses

### ISSUE THREAD

**Issue by tobidwest** [bytefury/crater#441] opened 2021-04-10 15:27 UTC
**Describe the bug**
When editing an expense, the expense category and client filed aren't prefilled.

**Expected behavior**
The existing data should be kept and displayed in the fields.

**Please complete the following information:**
- Crater version: 4.0.4
- PHP version: Not applicable
- Database type and version: Not applicable

**Comment by mohitpanjwani** [comment] 2021-05-06 09:03
I cannot seem to reproduce this. Mayb the data wasn't loaded yet? 

It seems to work perfectly on demo.craterapp.com.

**Comment by tobidwest** [comment] 2021-05-16 18:57
Thank you for reaching back, @mohitpanjwani. Now the preview works fine but Crater started displaying an error when trying to download the file:
![image](https://user-images.githubusercontent.com/61382793/118409130-463b5380-b689-11eb-9a6c-efc85d75d394.png)

Also, the category and the customer aren't saved.

**Comment by mohitpanjwani** [comment] 2021-05-24 10:59
It should log the error on storage/logs/laravel.log but that only if there's an exception. 

Can you check if you get something on your browser console or network tab?

**Comment by mohitpanjwani** [comment] 2021-05-24 11:00
> Thank you for reaching back, @mohitpanjwani. Does Crater log any errors or how can I help you to find the bug?

I edited your reply by mistake :P

**Comment by mohitpanjwani** [comment] 2021-06-24 12:12
Closing this as we cannot reproduce this issue.

**Closed by mohitpanjwani** 2021-06-24 12:12 UTC

**Comment by tobidwest** [comment] 2021-08-02 12:54
Sorry for my late reply. Unfortunately, the issue persists. I'm getting this in console:
![image](https://user-images.githubusercontent.com/61382793/127865047-3738c922-6790-47ab-8a97-83dc3ea7d8f8.png)

There's no recent event in the error log.
