### ISSUE TITLE
SQL error creating invoice

### ISSUE THREAD

**Issue by barf** [bytefury/crater#351] opened 2021-01-19 23:51 UTC
**Describe the bug**
An SQL error occurs when creating invoices.

To reproduce, create an invoice with per-item tax applied, following an upgrade from 3.x to 4

**Error**
[2021-01-19 17:56:17] production.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: "249911.1"

The insert query is as below:
```
SQL: insert into "invoices" ("due_date", "invoice_date", "discount_type", "discount", "invoice_template_id", "notes", "user_id", "invoice_number", "total", "sub_total", "tax", "discount_val", "creator_id", "status", "company_id", "paid_status", "tax_per_item", "discount_per_item", "due_amount", "updated_at", "created_at") values (2021-01-26 17:56:17, 2021-01-19 17:56:17, fixed, 0, 1, ?, 11, INV-000033, 249911.1, 217314, 0, 0, 1, DRAFT, 1, UNPAID, YES, NO, 249911.1, 2021-01-19 17:56:17, 2021-01-19 17:56:17) returning "id")
```

**Please complete the following information:**
- Crater version: 4.0.3
- PHP version: 7.4
- Database type and version: postgres (PostgreSQL) 12.5

**Optional info**
- OS:  Ubuntu
- Browser: Firefox

**Comment by barf** [comment] 2021-01-22 03:18
Ok this install has completely broken itself. Creating invoices over $1000 in total value results in HTTP 500, and adding items to invoices with per-item tax result in HTTP 500 also (with this same type error above).

**Comment by mohitpanjwani** [comment] 2021-01-22 03:37
I think it’s only happening on PostgreSQL. I will try to reproduce this issue and get back to you.

**Comment by barf** [comment] 2021-01-22 04:01
Thank you for your help!

To reproduce it, I add an item just under $1000, then apply a tax which brings the total over $1000, as shown below:
![image](https://user-images.githubusercontent.com/584684/105444828-78d4d100-5cd3-11eb-94d8-a80f0b16438c.png)

**Comment by barf** [comment] 2021-01-22 04:24
Also, if I remove the Tax from this invoice, it will save OK - applying the Tax seems to introduce the problem.

**Comment by mohitpanjwani** [comment] 2021-01-22 09:24
I've fixed this issue and deployed a new release: https://github.com/bytefury/crater/releases/tag/4.0.4

Can you please check it out and let me know if still happens? 

Make sure to update your crater app from Settings -> Update app to Version `4.0.0`

**Comment by barf** [comment] 2021-01-22 10:45
Can confirm it's fixed! Thank you for your work!!

**Comment by barf** [comment] 2021-01-23 08:39
Hi sorry to re-open this, but I can reproduce it on the mobile app also.
Same error:
```
[2021-01-23 21:32:26] production.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: "112213.55"
```

**Comment by mohitpanjwani** [comment] 2021-01-29 04:15
> Hi sorry to re-open this, but I can reproduce it on the mobile app also.
> Same error:
> 
> ```
> [2021-01-23 21:32:26] production.ERROR: SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for type bigint: "112213.55"
> ```

Thanks for the heads up. We’re working on it.

**Comment by barf** [comment] 2021-03-06 08:08
Hi Mohit, is there any update on this issue?

It breaks ability to create/update invoices on Android with PostgreSQL backends.

**Comment by mohitpanjwani** [comment] 2021-03-10 07:33
> Hi Mohit, is there any update on this issue?
> 
> It breaks ability to create/update invoices on Android with PostgreSQL backends.

Hi @barf, This is actually an issue with mobile frontend which will require a new update on Playstore/Appstore. 

We fixed this on Web frontend by rounding the currency but its remaining on mobile apps. The reason why this issue doesn't happen on mysql because it automatically converts the float value to integer instead of throwing an exception like Postgres does. 

Our RN (Mobile Developer) is busy on a different project so things got delayed but we've planned an update for this fix together with Face/Touch ID support by end of March. 

I'll notify you as soon as the update is live. 

Meanwhile I hope you can continue using the web version without any issues. 

Thank you for your patience :)

**Comment by mohitpanjwani** [comment] 2021-06-15 13:43
Issue fixed in the latest app update 👍

**Closed by mohitpanjwani** 2021-06-15 13:43 UTC
Labels: bug
